### ISSUE TITLE
Error ' ...does not provide an export named 'jsx' '

### ISSUE THREAD

**Issue by DrUNE** [vitejs/vite-plugin-react-pages#132]
Hi, when i update dependency @vitejs/plugin-react in library-monorepo-demo to latest version 4.0.0 i get error after starting app in dev
<img width="1598" alt="image" src="https://user-images.githubusercontent.com/843964/236452708-59a39fd2-75f0-4740-a9e9-73f7f1d2b2e1.png">
The rest npm scripts ( build or ssr )continue working fine.
There is any thing i should configure to make dev script to function properly?

**Comment by csr632** [comment]
I think it is caused by https://github.com/vitejs/vite-plugin-react/pull/132 introduced in @vitejs/plugin-react@4.0.0 .
Currently you can work around it by adding this vite config:
```
// vite.config.js

optimizeDeps: {
    include: ["react/jsx-runtime", "react/jsx-dev-runtime"]
}

```

I will look into it and find the actual fix in this weekend.

**Comment by csr632** [comment]
> is this something wanted to run the production mode of React in dev?

I think it should support "react/jsx-runtime" during dev.

Because npm packages may have transform their jsx code into js code with "react/jsx-runtime". And user may use these packages during dev. That cause "react/jsx-runtime" imported during dev.

In this specific case, our framework have some client code that is pre-built (when publishing npm package) into js code with "react/jsx-runtime":
https://unpkg.com/browse/vite-plugin-react-pages@4.1.1/dist/client-bundles/entries/App-f51ce870.js

**Comment by ArnaudBarre** [comment]
I'm surprised that this is not pick by Vite if this is in the dependency code. Sounds like very common to have a lib use in dev that is only present in node_modules

**Comment by csr632** [comment]
Yes. If the npm package is optimized by vite, importing `react/jsx-runtime` would not being an issue, because vite optimization will take care of cjs interop. But I think `@vitejs/plugin-react` should not rely on vite optimization because there are many complicated reason that make vite skip optimizing some packages.

In this specific case, I [add `vite-plugin-react-pages` to `optimizeDeps.exclude`](https://github.com/vitejs/vite-plugin-react-pages/blob/c907e39863e8ce4bb37dd05e2b8ac97e380f7189/packages/react-pages/src/node/index.ts#L83) because I have pre-bundled the package code to save some optimization time for users.

**Comment by ArnaudBarre** [comment]
The small issue here is that now all users will pre-bundle this package even if not used.

I'm surprised that the missing entry creates an error instead of late optimisation + page reload on cold start

**Comment by csr632** [comment]
> I'm surprised that the missing entry creates an error instead of late optimisation + page reload on cold start
You are right. Vite should found out that some imported package need optimization.

I have created a reproduction: https://stackblitz.com/edit/vitejs-vite-euyrbc?file=src%2FApp.tsx,vite.config.ts,package.json&terminal=dev

mui encounter similar issue with prop-types in this demo. We have to add mui package to `optimizeDeps.exclude` to see that error.

**Comment by csr632** [comment]
I fix this in on vite-plugin-react-pages's side by adding `react/jsx-runtime` to `optimizeDeps.include`.
https://github.com/vitejs/vite-plugin-react-pages/commit/193d4e93137bb70ae295dd56f8c7a18c3282f46e

By the way, I think vite (or @vitejs/plugin-react) can do better on their side.
