### ISSUE TITLE
The right anchor disappeared on some pages.

### ISSUE THREAD

**Issue by zbczbc2006** [vitejs/vite-plugin-react-pages#173]
[library demo](https://stackblitz.com/fork/github/vitejs/vite-plugin-react-pages/tree/main/packages/create-project/template-lib?file=README.md&terminal=dev)

 In the above demo, the right anchor disappeared on introduction page and  all components pages.

**Comment by csr632** [comment]
The right anchors (outlines) are **statically** extracted from markdown file.
The `Introduction` page in your demo don't have right anchors because the markdown file content is like:
```
---
title: Introduction
---

import README from '../../README.md';
<README />
```
Which actually don't have any title if we look at it statically (without running its code)! 

In real practice, It is not recommended to import and render a component with title like this. For several reasons:
- It is hard to extract outline info (title info / right anchors) of all pages statically if you do this. We have to extract outline info **statically** because the top search needs outline info of **all pages**. Otherwise, we need to render all page components to get the outline info, which is impractical. 
- Markdown content with title is not reusable. For example, if you have a H2 title in the content, it might fit in some pages, but other pages might want the title to be H3 instead.

In real practice, we rarely import markdown component. If you really want the content, just copy the markdown text into the file.

---

The components pages don't have right anchors because the it didn't register outlineInfo data, which is need by the right anchors (outlines) component. You should add these lines here in `docs/vite.config.ts`:
```js
// register outlineInfo data
// it will be consumed by theme-doc
api.addPageData({
  pageId,
  key: 'outlineInfo',
  // the ?outlineInfo query will extract title info from the markdown file and return the data as a js module
  dataPath: `${absolute}?outlineInfo`,
});
```
![image](https://github.com/vitejs/vite-plugin-react-pages/assets/18747423/f7b0df8b-3568-4f85-8dd6-37ce4498d78d)

Here is an updated demo: https://stackblitz.com/edit/vitejs-vite-plugin-react-pages-mt9crq?file=docs%2Fvite.config.ts&terminal=dev

**Comment by zbczbc2006** [comment]
> "The components pages don't have right anchors" is a flaw of previous project templates. I have [updated the project templates](https://github.com/vitejs/vite-plugin-react-pages/commit/016cf6febf4c9c514f98413aeefa5ffb820f912b#diff-f02b6b52db2ef154fd5a0f2303cbde8e3fccd818ae40e3b500974991d6b12dfd), you can [open a new demo](https://stackblitz.com/fork/github/vitejs/vite-plugin-react-pages/tree/main/packages/create-project/template-lib?file=README.md&terminal=dev) and check it out.

It worked, thanks!
