### ISSUE TITLE
In findPages, users can't overwrite exist data set by other file

### ISSUE THREAD

**Issue by csr632** [vitejs/vite-plugin-react-pages#18]
https://github.com/vitejs/vite-plugin-react-pages/blob/8630b2e977c703c26cf32b2b11d2ca83dbbc5340/packages/playground/custom-find-pages/vite.config.ts#L35

In this line, I want to set page's title. But since a page is composed by multiple files. This title may have been set when another file was been processed. So this line will throw `addPageData conflict: staticData with key "title" already exists`.

So I am considering removing the conflict check and allow overwriting. The conflict check was added before `PageStrategy` API. I think it doesn't fit any more.

/cc @aleclarson

**Comment by aleclarson** [comment]
Another option is to add a `getPageData` helper so the strategy can decide whether to guard against overwriting. The page data object would be created if no page data exists yet.

```ts
const data = helpers.getPageData(pageId)
// overwrite
data.title = 'hello world'
// guard
data.title ||= 'hello world'
```

**Comment by csr632** [comment]
But If we let user to mutate the page data, the logic inside `addPageData` will be bypassed.

**Comment by aleclarson** [comment]
We can use a `Proxy` for that.

**Comment by csr632** [comment]
I want to keep it react setState style instead of the vue proxy style. 🤣

**Comment by aleclarson** [comment]
Imperative APIs are more flexible and just as understandable. No point in boxing yourself in with a rigid API like setState, unless you have a really good reason for it. React's core team came up with setState because they wanted renders to use immutable data for "time slicing" purposes. We have no need for such complexity.

**Comment by aleclarson** [comment]
While we *could* pass a `pagesData` object for every file, it seems inefficient, since not every file has its own page data. So I think `helpers.getPageData` makes more sense.

Maybe splitting them up into `getRuntimeData` and `getStaticData` is a better approach? Less `proxy.runtimeData` or `proxy.staticData` being repeated everywhere.

```ts
findPages: (root, { watchFiles, getRuntimeData, getStaticData }) =>
  watchFiles(root, globs, (file) => {
    const data = getRuntimeData(file) // Pass a file or pageId
    const staticData = getStaticData('pageId')

    // Edit to your heart's content.
    data.contributorList = ['...']
    staticData.title ||= 'Default title'
  })
```

**Comment by csr632** [comment]
Fixed by https://github.com/vitejs/vite-plugin-react-pages/pull/19
