### ISSUE TITLE
Can the filebased routing be used standalone?

### ISSUE THREAD

**Issue by thelinuxlich** [vitejs/vite-plugin-react-pages#4]
I would like to add a filebased routing implementation to my starter pack https://github.com/thelinuxlich/react-modern-starter

**Comment by csr632** [comment]
The filebased routing can't be used standalone. Because the routing mechanism is coupled with ssr, theming .etc. But I think you can implement a filebased routing plugin by your self. You can refer to this code from`vite-plugin-react-pages`: 
https://github.com/vitejs/vite-plugin-react-pages/blob/daab754690e75f1a30c6bd8ea7581c2af308b465/packages/react-pages/src/node/index.ts#L66 

In the client side, the bootstrap code will `import pageList from '@!virtual-modules/pages';` and [render routes with it](https://github.com/vitejs/vite-plugin-react-pages/blob/daab754690e75f1a30c6bd8ea7581c2af308b465/packages/react-pages/src/client/App.tsx#L17).

**Comment by thelinuxlich** [comment]
Oh, looking at the code it doesn't seem to have id support yet, so it's kinda on the same state as my poor-man's autorouting https://github.com/thelinuxlich/react-modern-starter/blob/main/src/AutoRouting.jsx

**Comment by csr632** [comment]
Do you mean url parameter? I actually just supported url parameter a couple minutes ago.
