### ISSUE TITLE
How to run packaged file in local，such as  open in browser “file:///xxxxx/library-demo/public/index.html”

### ISSUE THREAD

**Issue by suibu** [vitejs/vite-plugin-react-pages#42]
I want to deploy the docs to the GitLab Page。I found that the files in dir: public could not be opened statically. 
These are my steps：
1、```npm init vite-pages library-demo --template lib ```

2、vite output dir: 'public' (Let the output directory be 'public ')

3、  ```npm run build:page```

```
 "scripts": {
    "build:page": "rm -rf public && vite build --config ./vite.config.ts",
  },
```
4、select the file:'public/index.html' to run in the browser

Can you give me some advice? thx.

**Comment by csr632** [comment]
In your step 4, you need to **serve your files with an http serever**, not opening the file in browser. Because browser treat `file://` and `http(s)://` protocal differently.

For example, in your step 4, you can install [serve](https://www.npmjs.com/package/serve) globally by `npm i -g serve`, then `serve -s ./public`.
