### ISSUE TITLE
Support React 18?

### ISSUE THREAD

**Issue by yunsii** [vitejs/vite-plugin-react-pages#73]
Whether consider support React 18?

**Comment by csr632** [comment]
Yes!

**Comment by yunsii** [comment]
Is it coming soon? I'm using vite-plugin-react-pages to custom my [starter-vite-react-library](https://github.com/yunsii/starter-vite-react-library)[WIP], and it's not easy to integrate with PageStrategy as my mind 😂

**Comment by csr632** [comment]
What problem do you encounter with `PageStrategy` ? It is related to React 18?

**Comment by csr632** [comment]
> Is it coming soon?

I expect one week of work to do the migration (React Router 6 + React 18).

**Comment by yunsii** [comment]
> What problem do you encounter with `PageStrategy` ? It is related to React 18?

No, just react-dom warning in console. Convention over configuration, maybe provide a official PageStrategy auto load page data is better. like: https://d.umijs.org/guide/basic

**Comment by csr632** [comment]
> > What problem do you encounter with `PageStrategy` ? It is related to React 18?
> 
> Convention over configuration, maybe provide a official PageStrategy auto load page data is better. like: https://d.umijs.org/guide/basic

Agreed. Currently [the default "convention"](https://vitejs.github.io/vite-plugin-react-pages/fs-routing) is only suitable for app. I should provide a `PageStrategy` that can be reused by library developer. dumi is indeed a great project to learn from.

**Comment by yunsii** [comment]
Maybe I can do something for the repo, is there a roadmap?

**Comment by csr632** [comment]
That would be greate! Contributions are very welcome. You can start with writing (or improve) [playground](https://github.com/vitejs/vite-plugin-react-pages/tree/main/packages/playground) and [template](https://github.com/vitejs/vite-plugin-react-pages/tree/main/packages/create-project/template-lib) (demos) to satisfy specific needs of users. 
For example, [your library template](https://github.com/yunsii/starter-vite-react-library) would be a great demo for users that want to create a library. Currently [our library template](https://github.com/vitejs/vite-plugin-react-pages/tree/main/packages/create-project/template-lib) is not very practical because it doesn't include build scripts to build the library (it only have scripts to run and build **demo**). The document site in the demo is also not very practical.

We need to create more practical and complex demos (we can learn from [docusaurus](https://docusaurus.io/), [dumi](https://d.umijs.org/), and [storybook.js](https://storybook.js.org/)). By doing that, we can know what features are valuable for users, and implement them in the theme-doc or vite-pages-core! Hopefully, you will be familiar with this repo by then, and be able to implement those features!



> is there a roadmap?

I use [issues](https://github.com/vitejs/vite-plugin-react-pages/issues) to track TODO (clear feature demand) . I have some vague ideas in my mind (such as more powerful demo rendering like storybook.js, better TS interface info extraction), but they are not clearly designed yet.

**Comment by yunsii** [comment]
Great, start with my lib template is good idea, but there is a question, how to integrate with my template, I will improve it continuously. By init script or others?

**Comment by csr632** [comment]
> Great, start with my lib template is good idea, but there is a question, how to integrate with my template, I will improve it continuously. By init script or others?

You can continue improve your template in your repo. And when it is ready, we can [add a build script before publishing create-vite-pages](create-vite-pages) to pull your template into this package.

**Comment by yunsii** [comment]
So where to place `pull-template-lib` script? I'm not understand.

**Comment by csr632** [comment]
In the package.json of create-vite-pages: https://github.com/vitejs/vite-plugin-react-pages/issues/create-vite-pages

I will run the script before publishing the package.

**Comment by csr632** [comment]
I just updated the url in the previous comment. Sorry for the broken url 😂

**Comment by yunsii** [comment]
Got it. I'm working on it now, the aim today is working as my expected routes 😂

**Comment by Evansy** [comment]
@csr632 Is it updated?

**Comment by csr632** [comment]
> @csr632 Is it updated?

Sorry for the delay! I haven't implement it because of lack of time. But since somebody have request for it, I will put more priority on it. I will implement this in a week.

**Comment by qiaogaolong** [comment]
@csr632 are waiting哈哈😂

**Comment by qiaogaolong** [comment]
@csr632 How long will it take for React Router 6 + React 18 to release a version，

**Comment by csr632** [comment]
> @csr632 How long will it take for React Router 6 + React 18 to release a version，

I am working on a version that:
- upgrade react to 18.x (will fix this issue)
- upgrade react-router to 6.x (will fix https://github.com/vitejs/vite-plugin-react-pages/issues/72)
- upgrade mdx to 2.x (will fix https://github.com/vitejs/vite-plugin-react-pages/issues/69)

And it will be a new major version. I will release an alpha version this week.

**Comment by qiaogaolong** [comment]
@csr632 Thanks for your hard work，If it is successful, please tell me, I will always pay attention

**Comment by csr632** [comment]
A new alfa version is published, check it out:
https://github.com/vitejs/vite-plugin-react-pages/pull/96
