### ISSUE TITLE
Effect of theme-doc antd global css

### ISSUE THREAD

**Issue by yunsii** [vitejs/vite-plugin-react-pages#93]
If I use theme doc to develop ui library, antd global css will also apply to my custom ui components. I have to override style mannually, how to make a workaround to the situation?

Maybe create a new theme without global css?

**Comment by csr632** [comment]
The style of theme-doc should not affect your antd components, because antd components owned by theme-doc have special classname prefix: `vp-antd-`
![image](https://user-images.githubusercontent.com/18747423/194924076-1b83c6a8-2566-45fd-90c1-8be215a449d5.png)

Instead, the antd components rendered by uses should have the default classname prefix: `ant-`
![image](https://user-images.githubusercontent.com/18747423/194925104-a9c2abb7-0064-4641-b665-2d99a6197d71.png)

Here is an online example: https://stackblitz.com/edit/vitejs-vite-plugin-react-pages-s2qrph?file=pages%2F_theme.tsx,pages%2Findex%24.tsx&terminal=dev

**Comment by yunsii** [comment]
global.less like this: https://github.com/ant-design/ant-design/blob/master/components/style/core/global.less#L104

**Comment by csr632** [comment]
These are only css reset style. They should not cause problem even if duplicated. Why do you want to override these style?

**Comment by yunsii** [comment]
![image](https://user-images.githubusercontent.com/18096089/195754613-9139e0d5-3bcb-49a2-ad75-ce755f8f01f2.png)
The global reset style includes antd theme variables. If I develop components with tailwindcss only?

**Comment by csr632** [comment]
> The global reset style includes antd theme variables. If I develop components with tailwindcss only?

These kind of style can be easily overwritten by applying yor antd style after theme-doc's antd style. The latter style rule wins.

**Comment by csr632** [comment]
> How about if I develop components without antd?

> If I develop components with tailwindcss only?

Oh, do you means you don't use antd in your app? I just realized what you means...

**Comment by yunsii** [comment]
It's not a bad idea, but need extra mental burden 😂 I think create a theme without global style is a better solution.

**Comment by csr632** [comment]
> It's not a bad idea, but need extra mental burden 😂 I think create a theme without global style is a better solution.

You are right. I have updated the them-doc in a beta version: `vite-pages-theme-doc@3.4.0-beta.0`. It has no global reset style from antd. Could you try it out?

**Comment by yunsii** [comment]
Sorry for so late to reply, I already used `vite-pages-theme-doc@3.4.0-beta.2`, but forgot what style effected, I think I will feedback  a little bit later more.

**Comment by csr632** [comment]
Published `vite-pages-theme-doc@3.4.0`.
